# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab04ada1ab441618b4642c3db11d83a14270826ba5cdec835b6f626e5eb982f58b07e6c9ad083575832c5c1b8945e4e59e6361aaf4d0579c7389e8acf391481a

test:
  secret_key_base: ab672158843d268e3c6bfc54bf5c7c9aeb89a7e8336cafbdc77ed6c8394880624db892305794f85ee6cdb8b747dbbe363ff077e9ca30fa124af61fccf59e54f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
